<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1" import="com.cs336.pkg.*"%>
    <%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*"%>
<!DOCTYPE html>
<html>
<head>
<style>
* {
    box-sizing: border-box;
}
.headerbox{
	float: left;
	width: 100%;
	padding-left: 30px;
}

.box {
    float: left;
    width: 33.33%;
    padding: 5px;
    padding-left: 55px;
}

.clearfix::after {
    content: "";
    clear: both;
    display: table;
}
</style>
</head>
<body>
	<%if(session.getAttribute("user")== null) {
	%> Login Error, Please Try Again. <br>
	<%}else{ %>
	Welcome, <%= session.getAttribute("user") %>!
	<%} %><a href = 'logout.jsp'>    Logout</a>


	<div class = "clearfix">
	<div class="headerbox" style= "background-color:#bbb">
		<h2><a href ="mainAdminPage.jsp">Buy Me!</a></h2>
	</div>
	</div>
	<br>
	<div class="clearfix">
  		<div class="box" style="background-color:#bbb">
   			 <p><a href = "changeCSAccounts.jsp">Customer Service Accounts</a></p>
  		</div>
  		<div class="box" style="background-color:#ccc">
    		<p><a href = "salesReport.jsp">Generate Sales Report</a></p>
  		</div>
 		 <div class="box" style="background-color:#ddd">
   			 <p><a href= "customerQuestions.jsp">Customer Questions</a></p>
  		</div>
	</div>
<br>
<br>
<div class = "clearfix">
	<div class="sub_headerbox" style= "background-color:#ddd">
		<h3>Total Earnings Generated</h3>
	</div>
	</div>
	<%
	try{
		//Get the database connection
		ApplicationDB db = new ApplicationDB();	
		Connection con = db.getConnection();
		String total_earnings_qr = "Select sum(bid.total) as `tot` From (select max(b.val) as total" +
						" from Bids b, Cellphone_Auctions cell, Headphone_Auctions h, Computer_Auctions comp" +
						" where (b.auction_id = cell.auction_id AND cell.status = 'closed')" +
						" or (b.auction_id = h.auction_id AND h.status = 'closed')" +
						" or (b.auction_id = comp.auction_id AND comp.status = 'closed')"+
						" Group By b.auction_id) as bid ";
		PreparedStatement tot_ps = con.prepareStatement(total_earnings_qr);
		ResultSet tot_rs = tot_ps.executeQuery();
		while(tot_rs.next()){
			out.print("$" + tot_rs.getString("tot"));
		}
		%>
		
		<div class = "clearfix">
	<div class="sub_headerbox" style= "background-color:#ddd">
		<h3>Total Earnings Generated By Item Sold</h3>
	</div>
	</div>	
		<%
		String auction_earnings_qr = "select b.auction_id as aID, max(b.val) as tot" +
									" from Bids b, Cellphone_Auctions cell, Headphone_Auctions h, Computer_Auctions comp" +
									" where (b.auction_id = cell.auction_id AND cell.status = 'closed')" +
									" or (b.auction_id = h.auction_id AND h.status = 'closed')" +
									" or (b.auction_id = comp.auction_id AND comp.status = 'closed')"
									+ "Group By b.auction_id";
		PreparedStatement ae_ps = con.prepareStatement(auction_earnings_qr);
		ResultSet ae_rs = ae_ps.executeQuery();
		//create table
		out.print("<table>");
		
		//row1
		out.print("<tr>"); 
		//column 1
		out.print("<td>"); out.print("Auction ID"); out.print("</td>");
		//column 2
		out.print("<td>"); out.print("Earnings"); out.print("</td>");
		out.print("</tr>");
		
		while(ae_rs.next()){
			out.print("<tr>"); 
			//column 1
			out.print("<td>"); out.print(ae_rs.getString("aID")); out.print("</td>");
			//column 2
			out.print("<td>"); out.print("$" + ae_rs.getString("tot")); out.print("</td>");
			out.print("</tr>");
		}
		
		out.print("</table>");
		%>
		<div class = "clearfix">
	<div class="sub_headerbox" style= "background-color:#ddd">
		<h3>Total Earnings Generated By Item Type</h3>
	</div>
	</div>	
		<% 
	 	 String headphone_sales_qr = "select sum(b.tot) as total"
	  								+ " from (select auction_id, max(val) as tot from Bids group by auction_id) as b, Headphone_Auctions c"
	  								+ " where b.auction_id = c.auction_id"
	  								+" and c.status = 'closed'";
		
		 String cellphone_sales_qr = "select sum(b.tot) as total"
					+ " from (select auction_id, max(val) as tot from Bids group by auction_id) as b, Cellphone_Auctions c"
					+ " where b.auction_id = c.auction_id"
					+" and c.status = 'closed'";
		 
		 String computer_sales_qr = "select sum(b.tot) as total"
					+ " from (select auction_id, max(val) as tot from Bids group by auction_id) as b, Computer_Auctions c"
					+ " where b.auction_id = c.auction_id"
					+" and c.status = 'closed'";
		 PreparedStatement hs_ps =con.prepareStatement(headphone_sales_qr);
		 PreparedStatement cell_ps = con.prepareStatement(cellphone_sales_qr);
		 PreparedStatement comp_ps = con.prepareStatement(computer_sales_qr);
		 ResultSet hs_rs = hs_ps.executeQuery();
		 while(hs_rs.next()){
			 out.print("Headphone Sales Income: $" + hs_rs.getString("total"));
			 out.print("<br>");
		 }
		 out.print("<br>");
		 ResultSet cell_rs = cell_ps.executeQuery();
		 while(cell_rs.next()){
			 out.print("Cellphone Sales Income: $" + cell_rs.getString("total"));
			 out.print("<br>");
		 }
		 out.print("<br>");
		 ResultSet comp_rs = comp_ps.executeQuery();
		 while(comp_rs.next()){
			 out.print("Computer Sales Income: $" + comp_rs.getString("total"));
			 out.print("<br>");
		 }%>
		 <div class = "clearfix">
	<div class="sub_headerbox" style= "background-color:#ddd">
		<h3>Total Earnings Generated By End-User</h3>
	</div>
	</div>	
		 <%
		String end_user_qr = "select user_id, sum(earnings) as sum from(select user_id, c.auction_id, b.val as earnings"
				+ " from Cellphone_Auctions c, (Select auction_id, max(val) as val from Bids group by auction_id) as b"
				+ " where status = 'closed' and c.auction_id = b.auction_id union"
				+ " select user_id, c.auction_id, b.val as earnings"
				+ " from Headphone_Auctions c, (Select auction_id, max(val) as val from Bids group by auction_id) as b"
				+ " where status = 'closed' and c.auction_id = b.auction_id union"
				+ " select user_id, c.auction_id, b.val as earnings"
				+ " from Computer_Auctions c, (Select auction_id, max(val) as val from Bids group by auction_id) as b "
				+ " where status = 'closed' and c.auction_id = b.auction_id) as B group by user_id";
		 
		 PreparedStatement eu_ps = con.prepareStatement(end_user_qr);
		 ResultSet eu_rs = eu_ps.executeQuery();
		 
		//create table
			out.print("<table>");
			
			//row1
			out.print("<tr>"); 
			//column 1
			out.print("<td>"); out.print("User ID"); out.print("</td>");
			//column 2
			out.print("<td>"); out.print("Earnings"); out.print("</td>");
			out.print("</tr>");
			
			while(eu_rs.next()){
				out.print("<tr>"); 
				//column 1
				out.print("<td>"); out.print(eu_rs.getString("user_id")); out.print("</td>");
				//column 2
				out.print("<td>"); out.print("$" + eu_rs.getString("sum")); out.print("</td>");
				out.print("</tr>");
			}
			
			out.print("</table>");
		 
		 
		con.close();
	}catch(Exception ex){
		out.print(ex);
	}
	%>
	
	
	
	

</body>
</html>
